image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - back-end/node_modules/

install_dependencies:
  stage: build
  script:
    - pwd
    - ls
    - whoami
    - cd back-end
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: echo "test"
