stages:
  - build
  - start

cache:
  paths:
    - back-end/node_modules/

build:
  stage: build
  script:
    - cat $NODE_ENV
    - echo $NODE_ENV
    - echo $CI_JOB_STAGE
    - cd back-end
    - npm install
  artifacts:
    paths:
      - back-end/node_modules/

start:
  stage: start
  script:
    - cd back-end
    - node index.js
