cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - front-end/node_modules/
    - back-end/node_modules/

stages:
  - build
  - test
  - start

build:
  stage: build
  script:
    - pwd
    - ls
    - cd front-end
    - npm install
    - npm run build:ui
    - cd ../back-end
    - npm install
    - ls
    # - docker system prune -a -f #remove previous docker stuff
    # - docker build -t theme-base .
    # # PROD DATABASE: - docker run -d -p 4000:4000 --name theme-base -e MONGODB_URI=$MONGODB_URI theme-base
    # - docker run -d -p 4000:4000 --name theme-base -e MONGODB_TEST_URI=$MONGODB_TEST_URI theme-base

test:
  stage: test
  script:
    - echo "test"

start:
  stage: start
  script:
    - echo "start"
