stages:
  - build
  - test
  - start

cache:
  paths:
    - back-end/node_modules/

build:
  stage: build
  script:
    - docker build -t theme-base .
    - docker run -p 4000:4000 -d theme-base --name theme-base
    - curl localhost:4000
  artifacts:
    paths:
      - back-end/node_modules/

test:
  stage: test
  script:
    - echo "test"

start:
  stage: start
  script:
    - echo "start"
